name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GOVER: '1.13.5'

trigger:
  batch: true
  branches:
    include: [ "master", "develop" ]
  paths:
    exclude: [ "README.md", "LICENSE", ".github/*", "examples/*", ".golangci.yml" ]

pr:
  autoCancel: true
  branches:
    include: [ "master", "develop" ]
  paths:
    exclude: [ "README.md", "LICENSE", ".github/*", "examples/*", ".golangci.yml" ]

jobs:
  - job: binary
    displayName: "binary build"
    pool:
      vmImage: "ubuntu-16.04"
    workspace:
      clean: all
    timeoutInMinutes: 15

    strategy:
      matrix:
        linux-amd64:
          GOOS: 'linux'
          GOARCH: 'amd64'
          FILENAME_SUFFIX: ''
        linux-arm:
          GOOS: 'linux'
          GOARCH: 'arm'
          FILENAME_SUFFIX: ''
        linux-arm64:
          GOOS: 'linux'
          GOARCH: 'arm64'
          FILENAME_SUFFIX: ''
        windows-amd64:
          GOOS: 'windows'
          GOARCH: 'amd64'
          FILENAME_SUFFIX: '.exe'
        darwin-amd64:
          GOOS: 'darwin'
          GOARCH: 'amd64'
          FILENAME_SUFFIX: ''

    steps:
    - task: GoTool@0
      displayName: 'Use Go'
      inputs:
        version: $(GOVER)

    - bash: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y upx
      displayName: 'Install Dependencies'
    - bash: |
        export GOPATH="/tmp/go"
        export GOBIN="/opt/hostedtoolcache/go/${GOVER}/x64/bin"
        export OUT_FILE="myip-${GOOS}-${GOARCH}${FILENAME_SUFFIX}"
        ./build.sh
        cp build/snd* ${BUILD_ARTIFACTSTAGINGDIRECTORY}
      displayName: 'Build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        ArtifactName: 'myip-$(GOOS)-$(GOARCH)'
